### ISSUE TITLE
Broken issue link (typo)

### ISSUE THREAD

**Issue by whoabuddy** [friedger/speed-spend#6]
When I log in, I am presented with a link to blockstack/ux#570 but it fails with a 404. The problem is the target contains `/issue/` when it should be should be `/issues/` 

![20200824_001_Selection](https://user-images.githubusercontent.com/9038904/91062570-bbd62f80-e5e1-11ea-9977-dc692bafe309.png)

https://github.com/blockstack/ux/issue/570

**Comment by friedger** [comment]
The issue was solved and the message has been removed. Thanks for trying speed-spend. I am happy to send you some hodl tokens.
